version: '3'
services:
  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - wiki_conf:/var/www/html/
    depends_on:
      - sql
      - parsoid
    links:
      - sql
      - parsoid

  sql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiki
      MYSQL_USER: wiki
      MYSQL_PASSWORD: wiki
      
  parsoid:
    image: thenets/parsoid:0.9
    ports:
      - "8000:8000"
    environment:
      PARSOID_DOMAIN_localhost: http://mediawiki/api.php

volumes:
  wiki_conf:
